services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "1000:1000"
    ports:
      - 8443:8080
    volumes:
      - /mnt/hdd/filebrowser/data:/data
      - /mnt/hdd/filebrowser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
