services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: "1000:1000"
    ports:
      - 8443:80
    volumes:
      - /mnt/hdd/filebrowser/srv:/srv
      - /mnt/hdd/filebrowser/database:/database
      - /mnt/hdd/filebrowser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
