services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: file-browser
    user: "1000:1000"
    ports:
      - 8443:80
    volumes:
      - ../../:/srv                            # Full HDD access
      - ./data/database:/database              # Database stored inside filebrowser/data
      - ./data/config:/config                  # Config stored inside filebrowser/data
    environment:
      - TZ=Asia/Kolkata
      - FB_BASEURL=/filebrowser
    restart: always
