services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest

    ports:
      - "53:53/tcp"        # DNS TCP
      - "53:53/udp"        # DNS UDP
      - "8081:80/tcp"      # Web interface (HTTP)
      - "8444:443/tcp"     # Web interface (HTTPS)

    environment:
      TZ: 'Asia/Kolkata'
      FTLCONF_webserver_api_password: 'pihole'
      FTLCONF_dns_listeningMode: 'all'

    volumes:
      - './etc-pihole:/etc/pihole'
      # Uncomment if you're migrating from v5 and used custom dnsmasq configs
      # - './etc-dnsmasq.d:/etc/dnsmasq.d'

    cap_add:
      # NET_ADMIN is not required unless you're using Pi-hole as a DHCP server
      - SYS_TIME       # Optional - allows container to sync system time
      - SYS_NICE       # Optional - improves DNS performance slightly

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost/admin/index.php"]
      interval: 30s
      timeout: 10s
      retries: 3
