services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"  # UID:GID for your user 'mcper'
    network_mode: 'host'
    volumes:
      - /home/mcper/docker/jellyfin/config:/config
      - /home/mcper/docker/jellyfin/cache:/cache
      - type: bind
        source: /mnt/hdd/data
        target: /media
      # Optional: add a second read-only media folder
      # - type: bind
      #   source: /mnt/hdd/media2
      #   target: /media2
      #   read_only: true
      # Optional: fonts for subtitle burn-in
      # - type: bind
      #   source: /usr/share/fonts
      #   target: /usr/local/share/fonts/custom
      #   read_only: true
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
      # Optional: used for DLNA / discovery
      # - JELLYFIN_PublishedServerUrl=http://192.168.31.100:8096
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Kolkata
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - /home/mcper/docker/jellyfin/jellyseerr/config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
